<script setup lang="ts">
import { computed, ref, watch } from 'vue';
import { useKeys } from '@/composables/meilisearch/useKeys';
import { useIndexes } from '@/composables/meilisearch/useIndexes';
import Button from 'primevue/button';
import DatePicker from 'primevue/datepicker';
import Drawer from 'primevue/drawer';
import InputText from 'primevue/inputtext';
import Textarea from 'primevue/textarea';
import Message from 'primevue/message';
import MultiSelect from 'primevue/multiselect';
import type { KeyCreation } from 'meilisearch';
import { useToast } from 'primevue';
import { CircleQuestionMark, Info } from 'lucide-vue-next';

const drawerOpen = defineModel<boolean>({ default: false });

const emit = defineEmits(['key-created']);

const toast = useToast();
const { indexes, isFetching: isFetchingIndexes, fetchAllIndexes } = useIndexes();
const { isLoading, createKey } = useKeys();

const indexOptions = computed(() => ['*', ...indexes.value.map((index) => index.uid)]);
const emptyKey = {
    uid: undefined,
    name: undefined,
    description: undefined,
    actions: [],
    indexes: [],
    expiresAt: null,
};
const newKey = ref<KeyCreation>(emptyKey);
function saveNewKey() {
    createKey(newKey.value).then(() => {
        toast.add({
            severity: 'success',
            summary: 'API Key Created',
            detail: `The API key: "${newKey.value.name}" was successfully created`,
            life: 3000,
        });
        drawerOpen.value = false;
        emit('key-created');
    }).catch((err) => {
        console.error(err);
    }).finally(() => {

    });
}
watch(newKey, (newVal) => {
    console.log('changed');
    if (newVal.uid === '') {
        delete newKey.value.uid;
    }
    if (newVal.name === '') {
        delete newKey.value.name;
    }
    if (newVal.description === '') {
        delete newKey.value.description;
    }
}, { deep: true });
</script>

<template>
    <Drawer
        v-model:visible="drawerOpen"
        header="New API Key"
        class="w-full sm:w-[40rem]"
        position="right"
        blockScroll
        @show="fetchAllIndexes"
    >
        <form
            class="space-y-6 sm:space-y-8"
            @submit.prevent="saveNewKey"
        >
            <div class="flex flex-col gap-2">
                <label for="new-key-uid">UID</label>
                <InputText
                    id="new-key-uid"
                    ref="name-input"
                    v-model="newKey.uid"
                    placeholder="optional - set UID"
                    type="text"
                    fluid
                />
                <Message>
                    <template #icon>
                        <Info />
                    </template>
                    <div class="text-sm">
                        A <a
                            href="https://www.sohamkamani.com/uuid-versions-explained/"
                            target="_blank"
                            class="text-inherit"
                        >uuid v4</a> to
                        identify the API key. If not specified, it is generated by Meilisearch
                    </div>
                </Message>
            </div>
            <div class="flex flex-col gap-2">
                <label for="name">Name</label>
                <InputText
                    id="new-key-name"
                    ref="name-input"
                    v-model="newKey.name"
                    placeholder="name your key"
                    type="text"
                    fluid
                />
            </div>
            <div class="flex flex-col gap-2">
                <label for="new-key-desc">Description</label>
                <Textarea
                    id="new-key-desc"
                    ref="name-input"
                    v-model="newKey.description"
                    placeholder="optional - set description"
                    rows="2"
                    autoResize
                    fluid
                />
            </div>
            <div class="flex flex-col gap-2">
                <label for="new-key-indexes">Indexes</label>
                <!-- TODO: watcher to see if * is selected, if so remove all other options -->
                <!-- TODO: wildcard index selected via input https://www.meilisearch.com/docs/reference/api/keys#indexes -->
                <MultiSelect
                    v-model="newKey.indexes"
                    pt:label:class="flex flex-wrap"
                    :options="indexOptions"
                    display="chip"
                    placeholder="select permitted indexes"
                    inputId="new-key-indexes"
                    :loading="isFetchingIndexes"
                    :showToggleAll="false"
                    showClear
                    filter
                    fluid
                />
            </div>
            <div class="flex flex-col gap-2">
                <label
                    for="new-key-actions"
                    class="flex items-center gap-2"
                >
                    <span>Actions</span>
                    <a
                        href="https://www.meilisearch.com/docs/reference/api/keys#actions"
                        target="_blank"
                        class="text-inherit"
                    >
                        <CircleQuestionMark />
                    </a>
                </label>
                <!-- TODO: watcher to see if * is selected, if so remove all other options -->
                <MultiSelect
                    v-model="newKey.indexes"
                    pt:label:class="flex flex-wrap"
                    :options="[
                        '*',
                        'search',
                        'documents.add',
                        'documents.get',
                        'documents.delete',
                        'indexes.create',
                        'indexes.get',
                        'indexes.update',
                        'indexes.delete',
                        'indexes.swap',
                        'tasks.get',
                        'tasks.cancel',
                        'tasks.delete',
                        'settings.get',
                        'settings.update',
                        'stats.get',
                        'dumps.create',
                        'snapshots.create',
                        'version',
                        'keys.get',
                        'keys.create',
                        'keys.update',
                        'keys.delete',
                        'network.get',
                        'network.update',
                        'chatCompletions',
                        'webhooks.get',
                        'webhooks.create',
                        'webhooks.update',
                        'webhooks.delete',
                    ]"
                    display="chip"
                    placeholder="select permitted actions"
                    inputId="new-key-actions"
                    :showToggleAll="false"
                    showClear
                    filter
                    fluid
                />
            </div>
            <div class="flex flex-col gap-2">
                <label for="new-key-expires">Expires At</label>
                <!-- TODO: normalize data to RFC 3339 format https://www.meilisearch.com/docs/reference/api/keys#expiresat -->
                <DatePicker
                    id="new-key-expires"
                    v-model="newKey.expiresAt"
                    placeholder="optional - select date & time"
                    hourFormat="12"
                    showTime
                    showButtonBar
                    fluid
                />
            </div>
            <div>
                <Button
                    type="submit"
                    label="Submit"
                    :loading="isLoading"
                />
            </div>
        </form>
    </Drawer>
</template>