/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppToast: typeof import('./src/components/primevue/AppToast.vue')['default']
    Breadcrumb: typeof import('./src/components/primevue/Breadcrumb.vue')['default']
    Button: typeof import('primevue/button')['default']
    Card: typeof import('primevue/card')['default']
    Checkbox: typeof import('primevue/checkbox')['default']
    Column: typeof import('primevue/column')['default']
    ConfirmDialog: typeof import('primevue/confirmdialog')['default']
    Container: typeof import('./src/components/Container.vue')['default']
    CreateIndexDrawer: typeof import('./src/components/meilisearch/CreateIndexDrawer.vue')['default']
    CreateKeyDrawer: typeof import('./src/components/meilisearch/CreateKeyDrawer.vue')['default']
    DataTable: typeof import('primevue/datatable')['default']
    DatePicker: typeof import('primevue/datepicker')['default']
    DeleteIndexDataDangerZone: typeof import('./src/components/meilisearch/DeleteIndexDataDangerZone.vue')['default']
    Drawer: typeof import('primevue/drawer')['default']
    EditKeyDrawer: typeof import('./src/components/meilisearch/EditKeyDrawer.vue')['default']
    Fieldset: typeof import('primevue/fieldset')['default']
    IndexTabMenu: typeof import('./src/components/meilisearch/IndexTabMenu.vue')['default']
    Inplace: typeof import('primevue/inplace')['default']
    InputErrors: typeof import('./src/components/InputErrors.vue')['default']
    InputGroup: typeof import('primevue/inputgroup')['default']
    InputGroupAddon: typeof import('primevue/inputgroupaddon')['default']
    InputText: typeof import('primevue/inputtext')['default']
    KeyDetailsDrawer: typeof import('./src/components/meilisearch/KeyDetailsDrawer.vue')['default']
    Menu: typeof import('./src/components/primevue/Menu.vue')['default']
    Menubar: typeof import('./src/components/primevue/Menubar.vue')['default']
    Message: typeof import('primevue/message')['default']
    MultiSelect: typeof import('primevue/multiselect')['default']
    NavLogoLink: typeof import('./src/components/NavLogoLink.vue')['default']
    PageTitleSection: typeof import('./src/components/PageTitleSection.vue')['default']
    PanelMenu: typeof import('./src/components/primevue/PanelMenu.vue')['default']
    ProgressSpinner: typeof import('primevue/progressspinner')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScrollTop: typeof import('primevue/scrolltop')['default']
    Select: typeof import('primevue/select')['default']
    SelectButton: typeof import('primevue/selectbutton')['default']
    SelectColorModeButton: typeof import('./src/components/SelectColorModeButton.vue')['default']
    Tab: typeof import('primevue/tab')['default']
    TabList: typeof import('primevue/tablist')['default']
    Tabs: typeof import('primevue/tabs')['default']
    Tag: typeof import('primevue/tag')['default']
    Textarea: typeof import('primevue/textarea')['default']
    ThemedJsonEditor: typeof import('./src/components/ThemedJsonEditor.vue')['default']
    Toast: typeof import('primevue/toast')['default']
    UpdateIndexPrimaryKeyForm: typeof import('./src/components/meilisearch/UpdateIndexPrimaryKeyForm.vue')['default']
  }
  export interface GlobalDirectives {
    Tooltip: typeof import('primevue/tooltip')['default']
  }
}
